name: Hello World

on:
  push:
    branches:
      - main

jobs:
  say_hello_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  display_time_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Display time
        run: |
          date
  display_directory_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Display directory
        run: |
          ls -l
