name: Hello World

on:
  push:
    branches:
      - main

jobs:
  say_hello_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
          date
          ls -l
