name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run tests
        run: npm run test
      - name: Build app
        run: npm run build
      - name: on failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: "Build failed!"
          description: |
            Commit `${{ github.event.head_commit }}` didn't build.
      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Trigger deployment
        env:
          COMMIT_CONTAINS: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}
        if: ${{ github.event_name == 'push' &&  env.COMMIT_CONTAINS == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: On deployment
        if: ${{ github.event_name == 'push' &&  success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          username: MrGithub
          nodetail: true
          description: Success!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        env:
          COMMIT_CONTAINS: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
        if: ${{ github.event_name == 'push'  &&  env.COMMIT_CONTAINS == 'false' }}
        uses: anothrNick/github-tag-action@1.71.0
